# k8s/overlays/production/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  PRODUCT_API_URL: "http://product-service-production:8000"
  ORDER_API_URL: "http://order-service-production:8001"