# k8s/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add a suffix to all resource names.
nameSuffix: -production

# Set the namespace for all resources.
namespace: production

resources:
  - ../../base
  - namespace.yaml

patches:
  - config-map.yaml
  