# .github/workflows/cd-pipeline.yml
# Workflow display name
name: CD - Deploy Services to AKS 

on:
  pull_request: # Trigger on pull request
    branches:
      - develop # Target develop branch
    paths: # Only when files change
      - 'backend/**'
      - 'frontend/**'

env: # Workflow environment variables
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  AKS_CLUSTER_NAME: 'SIT722-HD-AKS-Cluster'
  AKS_RESOURCE_GROUP: 'SIT722-HD-RG'
  IMAGE_TAG: ${{ github.sha }} # Use commit for tag

jobs:
  deploy_to_staging: # Staging deployment job
    runs-on: ubuntu-latest # Use GitHub runner
    environment: Staging # Target staging environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Get the latest code

      - name: Azure Login
        uses: azure/login@v1 # Authenticate with Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context
        uses: azure/aks-set-context@v3 # Connect to AKS cluster
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
      
      - name: Create Staging Namespace
        run: | # Ensure namespace exists
          kubectl create namespace staging --dry-run=client -o yaml | kubectl apply -f -

      - name: Create or Update Staging Secrets
        run: | # Apply Kubernetes secrets
          kubectl create secret generic ecomm-secrets-staging \
            --namespace=staging \
            --from-literal=POSTGRES_USER='${{ secrets.POSTGRES_USER }}' \
            --from-literal=POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' \
            --from-literal=AZURE_STORAGE_ACCOUNT_NAME='${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}' \
            --from-literal=AZURE_STORAGE_ACCOUNT_KEY='${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Update Kustomize and Deploy to Staging
        run: | # Deploy using Kustomize
          kubectl apply -k k8s/overlays/staging/

      - name: Verify staging deployments
        run: | # Check deployment status
          echo "Waiting for staging deployments to roll out..."
          kubectl rollout status deployment/frontend-staging -n staging
          kubectl rollout status deployment/product-service-staging -n staging
          kubectl rollout status deployment/order-service-staging -n staging
          echo "All services deployed to staging successfully!"

      - name: Logout from Azure
        if: always() # Always run this step
        run: az logout

  deploy_to_production: # Production deployment job
    runs-on: ubuntu-latest # Use GitHub runner
    needs: deploy_to_staging # Run after staging job
    environment: Production # Target production environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Get the latest code

      - name: Azure Login
        uses: azure/login@v1 # Authenticate with Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context
        uses: azure/aks-set-context@v3 # Connect to AKS cluster
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Create Production Namespace
        run: | # Ensure namespace exists
          kubectl create namespace production --dry-run=client -o yaml | kubectl apply -f -

      - name: Create or Update Production Secrets
        run: | # Apply Kubernetes secrets
          kubectl create secret generic ecomm-secrets-production \
            --namespace=production \
            --from-literal=POSTGRES_USER='${{ secrets.POSTGRES_USER }}' \
            --from-literal=POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' \
            --from-literal=AZURE_STORAGE_ACCOUNT_NAME='${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}' \
            --from-literal=AZURE_STORAGE_ACCOUNT_KEY='${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}' \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Update Kustomize and Deploy to Production
        run: | # Deploy using Kustomize
          kubectl apply -k k8s/overlays/production/

      - name: Verify production deployments
        run: | # Check deployment status
          echo "Waiting for production deployments to roll out..."
          kubectl rollout status deployment/frontend-production -n production
          kubectl rollout status deployment/product-service-production -n production
          kubectl rollout status deployment/order-service-production -n production
          echo "✅ All services deployed to production successfully!"

      - name: Logout from Azure
        if: always() # Always run this step
        run: az logout