# k8s/overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add a suffix to all resource names.
nameSuffix: -staging

# Set the namespace for all resources.
namespace: staging

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: config-map.yaml
  - path: ecomm-config-patch.yaml
    target:
      kind: ConfigMap
      name: ecomm-config